export default interface grocer {
    document_grocer: string,
    name_grocer: string,
    last_name_grocer: string,
    email_grocer: string,
    name_store: string,
    profile_photo_grocer?: string | null,
    cover_photo_grocer?: string | null,
    password_grocer: string,
    neighborhood: string,
    street: string,
    number_street: string,
    // apartment: string,
    number_grocer: string,
    department: string,
    city_grocer: string,
}